import { HeroPattern } from '@/components/HeroPattern'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={inter.className}>
      <body className='bg-zinc-900'>
        <Sidebar />

        <div className="ml-80 max-lg:ml-0 relative h-screen">
          <Header />
          <HeroPattern />

          <div className='py-24 px-8 max-w-4xl mx-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
